
name: pages build and deployment

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Fetch Lotto Draws (full/incremental with options)
        run: |
          python3 scripts/fetch_lotto.py --timeout 10 --retries 4 --retry-backoff 1.8 --sleep 0.12

      - name: Print status
        run: cat scripts/status.json || echo "no status.json"

      - name: Commit updated data (if changed)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/ scripts/status.json || true
          git commit -m "ci: update lotto draws [skip ci]" || echo "no changes"
          git push || echo "no push"

      - name: Slack alert on errors
        if: ${{ failure() && secrets.SLACK_WEBHOOK }}
        run: |
          OK=$(jq -r '.ok' scripts/status.json || echo "true")
          if [ "$OK" != "true" ]; then
            curl -X POST -H 'Content-type: application/json'               --data '{"text":"❌ Lotto fetch failed"}'               ${{ secrets.SLACK_WEBHOOK }}
          fi

      - name: Send email on errors
        if: ${{ failure() && secrets.MAIL_FROM && secrets.MAIL_TO && secrets.SMTP_HOST && secrets.SMTP_PORT && secrets.SMTP_USER && secrets.SMTP_PASS }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          secure: true
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "lotto-4: build failed (#${{ github.run_number }})"
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          html_body: |
            ❌ lotto-4 build failed
            Repo: ${{ github.repository }}
            Run:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
